name: Security Inquiry
description: Information about reporting security vulnerabilities
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ### IMPORTANT: Do NOT report vulnerabilities publicly.
        Please read our [Security Policy](../../SECURITY.md) to report vulnerabilities privately.
        Reports can be submitted through [GitHub Private Vulnerability Reporting](https://github.com/anubhav-n-mishra/ABS-Trace/security/advisories/new)
        or via email to **anubhav09.work@gmail.com**.
