// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Anubhav Mishra and Amvelt
import type { FeatureGraph } from '../core/graph.js';

export function generateFeatureIndexMarkdown(graph: FeatureGraph): string {
  const features = graph.getFeatures().sort((a, b) => a.displayName.localeCompare(b.displayName));

  let md = `<!-- @generated by Amvelt TRACE - DO NOT EDIT MANUALLY.
Canonical state lives in .codebase/ -->

# Feature Index

This document is a generated projection of the codebase feature graph maintained by **Amvelt TRACE**.
It maps high-level product features to their exact implementations, APIs, database models, and tests.

---
`;

  if (features.length === 0) {
    md += `\n*No features detected yet. Run \`trace init\` or define explicit features in \`.codebase/features/\`.*\n`;
    return md;
  }

  for (const feat of features) {
    const view = graph.getFeatureView(feat.urn);

    md += `\n## ${feat.displayName}\n\n`;
    if (feat.description) {
      md += `> ${feat.description}\n\n`;
    }

    md += `- **Confidence**: \`${feat.confidence}\` (${Math.round(feat.confidenceScore * 100)}%)\n`;
    if (feat.tags && feat.tags.length > 0) {
      md += `- **Tags**: ${feat.tags.map((t) => `\`${t}\``).join(', ')}\n`;
    }
    md += `\n`;

    // UI
    if (view.ui.length > 0) {
      md += `### UI Components\n`;
      for (const item of view.ui) {
        md += `- \`${item.node.path}:${item.node.startLine}-${item.node.endLine}\` — **${item.node.name}**\n`;
        if (item.evidence?.reason) {
          md += `  - *Evidence: ${item.evidence.reason}*\n`;
        }
      }
      md += `\n`;
    }

    // API
    if (view.api.length > 0) {
      md += `### API Endpoints\n`;
      for (const item of view.api) {
        md += `- \`${item.node.httpMethod} ${item.node.routePath}\` in \`${item.node.path}:${item.node.startLine}\`\n`;
        if (item.evidence?.reason) {
          md += `  - *Evidence: ${item.evidence.reason}*\n`;
        }
      }
      md += `\n`;
    }

    // Services / Logic
    if (view.services.length > 0) {
      md += `### Services & Business Logic\n`;
      for (const item of view.services) {
        md += `- \`${item.node.path}:${item.node.startLine}-${item.node.endLine}\` — **${item.node.name}** (${item.node.symbolKind})\n`;
        if (item.evidence?.reason) {
          md += `  - *Evidence: ${item.evidence.reason}*\n`;
        }
      }
      md += `\n`;
    }

    // Database Models
    if (view.database.length > 0) {
      md += `### Database Models\n`;
      for (const item of view.database) {
        md += `- \`${item.node.name}\` model in \`${item.node.path}:${item.node.startLine}\`\n`;
        if (item.evidence?.reason) {
          md += `  - *Evidence: ${item.evidence.reason}*\n`;
        }
      }
      md += `\n`;
    }

    // Tests
    if (view.tests.length > 0) {
      md += `### Tests\n`;
      for (const item of view.tests) {
        md += `- \`${item.node.path}:${item.node.startLine}\` — **${item.node.name}**\n`;
        if (item.evidence?.reason) {
          md += `  - *Evidence: ${item.evidence.reason}*\n`;
        }
      }
      md += `\n`;
    }

    // Consumers
    if (view.consumers.length > 0) {
      md += `### Consumers & Dependent Features\n`;
      for (const c of view.consumers) {
        md += `- **${c.featureName}**\n`;
      }
      md += `\n`;
    }

    md += `---\n`;
  }

  return md;
}
